name: main
on: [push, pull_request]
jobs:
  test:
    strategy:
      matrix:
        go-version: [1.13]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    name: Test [${{ matrix.os }}] go ${{ matrix.go-version }}
    steps:
    - name: Install Go
      uses: actions/setup-go@v1
      with:
        go-version: ${{ matrix.go-version }}

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run tests
      env:
        GOPROXY: "https://proxy.golang.org"
      run: go test -v ./...
